version: '3'
services:
  timescale_trade245:
    image: timescale/timescaledb:latest-pg11
    container_name: timescale_$PROJECT
    environment:
        - POSTGRES_USER=$PG_USER
        - POSTGRES_PASSWORD=$PG_PASSWORD
        - POSTGRES_DB=$PG_DB
        - PG_SYSTEM_SHARED_BUFFERS=256MB
    volumes:
      - /data/mt5_data/$PROJECT/data/export/:/var/lib/postgresql/data/
    ports:
      - "${PG_PORT}:${PG_PORT}"
  grafana_trade245:
    hostname: grafana
    container_name: grafana_$PROJECT
    image: grafana/grafana:$GRAFANA_VERSION
    environment:
      TZ: "Europe/Moscow"
      GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_ADMIN_PASSWORD
      GF_SECURITY_ADMIN_USER: $GRAFANA_ADMIN_USER
    expose:
      - 3132
    ports:
      - "${GRAFANA_PORT}:3000"
  loki_trade245:
    container_name: loki_$PROJECT
    image: grafana/loki:$LOKI_VERSION
    ports:
      - "${LOKI_PORT}:3100"
    command: -config.file=/etc/loki/local-config.yaml
  promtail_trade245:
    container_name: promtail_$PROJECT
    image: grafana/promtail:$PROMTAIL_VERSION
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml 
 
