version: '3'
services:
  timescale_trade245:
    image: timescale/timescaledb:latest-pg11
    container_name: "timescale_${PROJECT}"
    volumes:
      - /data/mt5_data/$PROJECT/data/export/:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER="${PG_USER}"
        - POSTGRES_PASSWORD="${PG_PASSWORD}"
        - POSTGRES_DB="${PG_DB}"
        - PG_SYSTEM_SHARED_BUFFERS=256MB
    ports:
      - "${PG_PORT}:${PG_PORT}"
  grafana_trade245:
    hostname: grafana
    container_name: "grafana_${PROJECT}"
    image: "grafana/grafana:${GRAFANA_VERSION}"
    environment:
      TZ: "Europe/Moscow"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}"
      GF_SECURITY_ADMIN_USER: "${GRAFANA_ADMIN_USER}"
    expose:
      - 3132
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - $WORKSPACE/dashboards/:/etc/grafana/provisioning/dashboards/
      - /projects/$PROJECT/grafana/:/etc/grafana/provisioning/datasources/
      - /data/mt5_data/$PROJECT/grafana/grafana-volume:/var/lib/grafana
      - /data/mt5_data/$PROJECT/grafana/log:/var/log 
